// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v7.35.1
// source: proto/registration/registration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_proto_registration_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{0}
}

func (x *Registration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Registration) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Registration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegistrationRequest) Reset() {
	*x = CreateRegistrationRequest{}
	mi := &file_proto_registration_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegistrationRequest) ProtoMessage() {}

func (x *CreateRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CreateRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRegistrationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRegistrationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationRequest) Reset() {
	*x = GetRegistrationRequest{}
	mi := &file_proto_registration_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationRequest) ProtoMessage() {}

func (x *GetRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationRequest.ProtoReflect.Descriptor instead.
func (*GetRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{2}
}

func (x *GetRegistrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationsRequest) Reset() {
	*x = GetRegistrationsRequest{}
	mi := &file_proto_registration_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationsRequest) ProtoMessage() {}

func (x *GetRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*GetRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{3}
}

func (x *GetRegistrationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistrationsResponse) Reset() {
	*x = GetRegistrationsResponse{}
	mi := &file_proto_registration_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistrationsResponse) ProtoMessage() {}

func (x *GetRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*GetRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{4}
}

func (x *GetRegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

type CancelRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationRequest) Reset() {
	*x = CancelRegistrationRequest{}
	mi := &file_proto_registration_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationRequest) ProtoMessage() {}

func (x *CancelRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CancelRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRegistrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationResponse) Reset() {
	*x = CancelRegistrationResponse{}
	mi := &file_proto_registration_registration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationResponse) ProtoMessage() {}

func (x *CancelRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CancelRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_registration_registration_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_registration_registration_proto protoreflect.FileDescriptor

const file_proto_registration_registration_proto_rawDesc = "" +
	"\n" +
	"%proto/registration/registration.proto\x12\fregistration\"j\n" +
	"\fRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"O\n" +
	"\x19CreateRegistrationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"(\n" +
	"\x16GetRegistrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x17GetRegistrationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"\x18GetRegistrationsResponse\x12@\n" +
	"\rregistrations\x18\x01 \x03(\v2\x1a.registration.RegistrationR\rregistrations\"+\n" +
	"\x19CancelRegistrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1aCancelRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x91\x03\n" +
	"\x13RegistrationService\x12Y\n" +
	"\x12CreateRegistration\x12'.registration.CreateRegistrationRequest\x1a\x1a.registration.Registration\x12S\n" +
	"\x0fGetRegistration\x12$.registration.GetRegistrationRequest\x1a\x1a.registration.Registration\x12a\n" +
	"\x10GetRegistrations\x12%.registration.GetRegistrationsRequest\x1a&.registration.GetRegistrationsResponse\x12g\n" +
	"\x12CancelRegistration\x12'.registration.CancelRegistrationRequest\x1a(.registration.CancelRegistrationResponseBGZEgithub.com/AbhiramiRajeev/event-ticketing-platform/proto/registrationb\x06proto3"

var (
	file_proto_registration_registration_proto_rawDescOnce sync.Once
	file_proto_registration_registration_proto_rawDescData []byte
)

func file_proto_registration_registration_proto_rawDescGZIP() []byte {
	file_proto_registration_registration_proto_rawDescOnce.Do(func() {
		file_proto_registration_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registration_registration_proto_rawDesc), len(file_proto_registration_registration_proto_rawDesc)))
	})
	return file_proto_registration_registration_proto_rawDescData
}

var file_proto_registration_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_registration_registration_proto_goTypes = []any{
	(*Registration)(nil),               // 0: registration.Registration
	(*CreateRegistrationRequest)(nil),  // 1: registration.CreateRegistrationRequest
	(*GetRegistrationRequest)(nil),     // 2: registration.GetRegistrationRequest
	(*GetRegistrationsRequest)(nil),    // 3: registration.GetRegistrationsRequest
	(*GetRegistrationsResponse)(nil),   // 4: registration.GetRegistrationsResponse
	(*CancelRegistrationRequest)(nil),  // 5: registration.CancelRegistrationRequest
	(*CancelRegistrationResponse)(nil), // 6: registration.CancelRegistrationResponse
}
var file_proto_registration_registration_proto_depIdxs = []int32{
	0, // 0: registration.GetRegistrationsResponse.registrations:type_name -> registration.Registration
	1, // 1: registration.RegistrationService.CreateRegistration:input_type -> registration.CreateRegistrationRequest
	2, // 2: registration.RegistrationService.GetRegistration:input_type -> registration.GetRegistrationRequest
	3, // 3: registration.RegistrationService.GetRegistrations:input_type -> registration.GetRegistrationsRequest
	5, // 4: registration.RegistrationService.CancelRegistration:input_type -> registration.CancelRegistrationRequest
	0, // 5: registration.RegistrationService.CreateRegistration:output_type -> registration.Registration
	0, // 6: registration.RegistrationService.GetRegistration:output_type -> registration.Registration
	4, // 7: registration.RegistrationService.GetRegistrations:output_type -> registration.GetRegistrationsResponse
	6, // 8: registration.RegistrationService.CancelRegistration:output_type -> registration.CancelRegistrationResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_registration_registration_proto_init() }
func file_proto_registration_registration_proto_init() {
	if File_proto_registration_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registration_registration_proto_rawDesc), len(file_proto_registration_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registration_registration_proto_goTypes,
		DependencyIndexes: file_proto_registration_registration_proto_depIdxs,
		MessageInfos:      file_proto_registration_registration_proto_msgTypes,
	}.Build()
	File_proto_registration_registration_proto = out.File
	file_proto_registration_registration_proto_goTypes = nil
	file_proto_registration_registration_proto_depIdxs = nil
}
